---
- name: Configurar parámetros sysctl para Kubernetes y desplegar Flannel
  hosts: all
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars_files:
    - vault.yml
  become: true
  tasks:
    # Configuración de sysctl para Kubernetes
    - name: Añadir parámetros de sysctl a /etc/sysctl.d/k8s.conf
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "net.ipv4.ip_forward = 1"
        create: yes  # Si el archivo no existe, lo creará.

    - name: Aplicar parámetros de sysctl sin reiniciar
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes  # Recarga los parámetros sin reiniciar el sistema.

    # Comprobar si el módulo 'br_netfilter' está cargado
    - name: Verificar si 'br_netfilter' está cargado
      command: lsmod | grep br_netfilter
      register: br_netfilter_loaded
      ignore_errors: true  # Si el comando falla, no detendrá el playbook

    - name: Cargar el módulo 'br_netfilter' si no está cargado
      command: sudo modprobe br_netfilter
      when: br_netfilter_loaded.rc != 0  # Solo si el módulo no está cargado

    # Aplicar cambios en sysctl sin reiniciar
    - name: Aplicar parámetros de sysctl
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: yes  # Recarga los parámetros sin reiniciar el sistema.


